version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=123
      - DB_NAME=dbcoba
    networks:
      - app-network
    depends_on:
      - mysql
    restart: always
    command: sh -c "sleep 10 && node index.js" # Menunggu 10 detik sebelum menjalankan aplikasi

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
    networks:
      - app-network

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "dbcoba"
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - D:\Erdin's\TUGAS\SEMESTER 5\Backend\docker_crud\mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - mysql

networks:
  app-network:
    driver: bridge
